language: rust
rust:
- stable
- beta
- nightly
env:
- FEATURES=std,nightly
- FEATURES=std
- FEATURES=nightly
- FEATURES=
matrix:
  exclude:
  - rust: stable
    env: FEATURES=std,nightly
  - rust: stable
    env: FEATURES=nightly
  - rust: beta
    env: FEATURES=std,nightly
  - rust: beta
    env: FEATURES=nightly
script:
- cargo build --verbose --no-default-features --features="$FEATURES"
- if [ "$FEATURES" = "std,nightly" ]; then cargo test --verbose --tests; fi
- if [ "$FEATURES" = "std,nightly" ]; then cargo test --verbose --doc; fi
- if [ "$FEATURES" = "std,nightly" ]; cargo doc --verbose; fi
- cargo test --verbose --example widget_tree_no_std --no-default-features --features="$FEATURES"
- if [ "$FEATURES" = "std,nightly" ]; then cargo test --verbose --example widget_tree; fi
- if [ "$FEATURES" = "std,nightly" ]; then cargo test --verbose --example widget_tree_generic; fi
