[package]
name = "components-arena"
version = "0.1.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = ["once_cell"]

[dependencies]
derivative = "2.1.1"
once_cell = { version = "1.4.0", optional = true }

[dev-dependencies]
macro-attr = "0.2.0"

[[example]]
name = "widget_tree"
required-features = ["std"]

[[example]]
name = "widget_tree_no_std"
