[package]
edition = "2018"
name = "components-arena"
version = "0.4.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "Simple library for creating complex domain-specific self-referential data structures."
readme = "README.md"
documentation = "https://docs.rs/components-arena/"
keywords = ["generational", "arena", "tree", "graph", "entity"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/components-arena"

[features]
default = ["std", "nightly"]
std = ["once_cell"]
nightly = []

[dependencies]
derivative = "2.1.1"
once_cell = { version = "1.4.0", optional = true }
either = { version = "1.5.3", features = [] }
rand = { version = "0.7.3", features = ["small_rng"] }

[dev-dependencies]
macro-attr = { version = "0.2.0", features = [] }
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"

[[example]]
name = "widget_tree"
required-features = ["std", "nightly"]

[[example]]
name = "widget_tree_generic"
required-features = ["std", "nightly"]

[[example]]
name = "widget_tree_no_std"
