[package]
edition = "2018"
name = "components-arena"
version = "1.2.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "Simple library for creating complex domain-specific self-referential data structures."
readme = "README.md"
documentation = "https://docs.rs/components-arena/"
keywords = ["generational", "arena", "tree", "graph", "entity"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/components-arena"

[features]
default = ["std", "nightly"]
std = ["phantom-type/std"]
nightly = []

[dependencies]
educe = "0.4.18"
either = { version = "1.5.3", default-features = false }
rand = { version = "0.8.4", default-features = false, features = ["small_rng"] }
generics = "0.2.7"
phantom-type = { version = "0.3.1", default-features = false }

[dev-dependencies]
macro-attr-2018 = "1.1.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[[example]]
name = "widget_tree"
required-features = ["std", "nightly"]

[[example]]
name = "widget_tree_generic"
required-features = ["std", "nightly"]

[[example]]
name = "widget_tree_no_std"
