[package]
name = "components-arena"
version = "0.1.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = []

[dependencies]
derivative = "2.1.1"
once_cell = "1.4.0"

[dev-dependencies]
macro-attr = "0.2.0"
