name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  traits:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: ["1.44", stable, beta, nightly]
        features: ["", "--features=nightly"]
        exclude:
        - rust: "1.44"
          features: "--features=nightly"
        - rust: stable
          features: "--features=nightly"
        - rust: beta
          features: "--features=nightly"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions/checkout@v2
    - name: detach from workspace
      uses: JesseTG/rm@v1.0.2
      with:
        path: Cargo.toml
    - run: "cargo build --verbose --no-default-features ${{ matrix.features }}"
      working-directory: traits
    - run: "cargo test --verbose --doc --no-default-features ${{ matrix.features }}"
      working-directory: traits
    - run: "cargo doc --verbose --no-default-features ${{ matrix.features }}"
      working-directory: traits
    - run: "cargo build --verbose --release --no-default-features ${{ matrix.features }}"
      working-directory: traits
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: ["1.71", stable, beta, nightly]
        features: ["", "--features=nightly"]
        exclude:
        - rust: "1.71"
          features: "--features=nightly"
        - rust: stable
          features: "--features=nightly"
        - rust: beta
          features: "--features=nightly"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - run: "rustup component add clippy"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose --workspace --no-default-features ${{ matrix.features }}"
    - run: "cargo test --verbose --workspace --tests --no-default-features ${{ matrix.features }}"
    - run: "cargo test --verbose --workspace --doc --no-default-features ${{ matrix.features }}"
    - run: "cargo doc --verbose --workspace --no-default-features ${{ matrix.features }}"
    - run: "cargo build --verbose --workspace --release --no-default-features ${{ matrix.features }}"
    - run: "cargo run --verbose --example widget_tree --no-default-features ${{ matrix.features }}"
    - run: "cargo run --verbose --example widget_tree_generic --no-default-features ${{ matrix.features }}"
    - run: "cargo outdated --verbose --workspace --root-deps-only --exit-code 1 ${{ matrix.features }}"
    - run: "cargo clippy --verbose --workspace --no-default-features ${{ matrix.features }}"
  ensure_no_std:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          triple: x86_64-unknown-linux-gnu
        - os: windows-latest
          triple: x86_64-pc-windows-msvc
        - os: macOS-latest
          triple: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add rust-src --toolchain nightly-${{ matrix.triple }}"
    - uses: actions/checkout@v2
    - run: "cargo +nightly build --verbose -Z build-std=core,alloc,panic_abort --target ${{ matrix.triple }} --release"
      working-directory: ensure_no_std
    - run: "./ensure_no_std/target/${{ matrix.triple }}/release/ensure_no_std"
